name: AI_GS
channels:
- conda-forge
- nvidia
- bioconda
dependencies:
- accelerate[version='>=1.0.0']
- nvidia::cuda
- nvidia::cuda-toolkit
- joblib[version='>=1.3.0']
- matplotlib[version='>=3.7.0']
- numpy[version='>=1.24.0']
- openpyxl[version='>=3.1.0']
- pandas[version='>=2.0.0']
- pip
- pyarrow[version='>=12.0.0']
- python[version='>=3.10,<3.12']
- pytorch[version='>=2.0.0']
- pyyaml[version='>=6.0']
- scikit-learn[version='>=1.3.0']
- torchmetrics[version='>=1.0.0']
- transformers[version='>=4.40.0']
- wandb[version='>=0.17.0']
- cuda-toolkit[version='>=11.3.0']
- mamba-ssm[version='>=1.2.0']
- causal-conv1d[version='>=1.2.0']
- r-base[version='>=4.5.0']
- r-dplyr
- r-tidyr
- r-stringr
- r-glue
- r-optparse
- r-jsonlite
- r-ggplot2
- r-ggpmisc
- r-bglr
- openblas